version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: dbsoftware-triagem
    environment:
      POSTGRES_DB: dbtriagem
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
      - "5430:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data:

