version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: dbsoftware-triagem
    environment:
      POSTGRES_DB: dbtriagem
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
      - "5430:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: [ "start-dev" ]
    ports:
      - "8080:8080"


volumes:
  db_data:

